apiVersion: v1
kind: Namespace
metadata:
  name: kopeio-auth-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: kopeio-auth-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      serviceAccountName: auth-server
      containers:
      - image: justinsb/auth-server:latest #ghcr.io/dexidp/dex:v2.30.0
        name: auth-server
        command:
        - /bin/auth-server
        
        ports:
        - name: http
          containerPort: 8080

        # readinessProbe: TODO
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: kopeio-auth-system
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: auth-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-server
  namespace: kopeio-auth-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auth-server
  namespace: kopeio-auth-system
rules:
- apiGroups: ["auth.kope.io"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["secrets"]
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-server
  namespace: kopeio-auth-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: auth-server
subjects:
- kind: ServiceAccount
  name: auth-server
  namespace: kopeio-auth-system