// +build !ignore_autogenerated

/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	componentconfig "kope.io/auth/pkg/apis/componentconfig"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_AuthConfiguration_To_componentconfig_AuthConfiguration,
		Convert_componentconfig_AuthConfiguration_To_v1alpha1_AuthConfiguration,
		Convert_v1alpha1_AuthConfigurationList_To_componentconfig_AuthConfigurationList,
		Convert_componentconfig_AuthConfigurationList_To_v1alpha1_AuthConfigurationList,
		Convert_v1alpha1_AuthProvider_To_componentconfig_AuthProvider,
		Convert_componentconfig_AuthProvider_To_v1alpha1_AuthProvider,
		Convert_v1alpha1_AuthProviderList_To_componentconfig_AuthProviderList,
		Convert_componentconfig_AuthProviderList_To_v1alpha1_AuthProviderList,
		Convert_v1alpha1_GenerateKubeconfig_To_componentconfig_GenerateKubeconfig,
		Convert_componentconfig_GenerateKubeconfig_To_v1alpha1_GenerateKubeconfig,
		Convert_v1alpha1_OAuthConfig_To_componentconfig_OAuthConfig,
		Convert_componentconfig_OAuthConfig_To_v1alpha1_OAuthConfig,
	)
}

func autoConvert_v1alpha1_AuthConfiguration_To_componentconfig_AuthConfiguration(in *AuthConfiguration, out *componentconfig.AuthConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_GenerateKubeconfig_To_componentconfig_GenerateKubeconfig(&in.GenerateKubeconfig, &out.GenerateKubeconfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_AuthConfiguration_To_componentconfig_AuthConfiguration is an autogenerated conversion function.
func Convert_v1alpha1_AuthConfiguration_To_componentconfig_AuthConfiguration(in *AuthConfiguration, out *componentconfig.AuthConfiguration, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthConfiguration_To_componentconfig_AuthConfiguration(in, out, s)
}

func autoConvert_componentconfig_AuthConfiguration_To_v1alpha1_AuthConfiguration(in *componentconfig.AuthConfiguration, out *AuthConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_componentconfig_GenerateKubeconfig_To_v1alpha1_GenerateKubeconfig(&in.GenerateKubeconfig, &out.GenerateKubeconfig, s); err != nil {
		return err
	}
	return nil
}

// Convert_componentconfig_AuthConfiguration_To_v1alpha1_AuthConfiguration is an autogenerated conversion function.
func Convert_componentconfig_AuthConfiguration_To_v1alpha1_AuthConfiguration(in *componentconfig.AuthConfiguration, out *AuthConfiguration, s conversion.Scope) error {
	return autoConvert_componentconfig_AuthConfiguration_To_v1alpha1_AuthConfiguration(in, out, s)
}

func autoConvert_v1alpha1_AuthConfigurationList_To_componentconfig_AuthConfigurationList(in *AuthConfigurationList, out *componentconfig.AuthConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]componentconfig.AuthConfiguration, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_AuthConfiguration_To_componentconfig_AuthConfiguration(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_AuthConfigurationList_To_componentconfig_AuthConfigurationList is an autogenerated conversion function.
func Convert_v1alpha1_AuthConfigurationList_To_componentconfig_AuthConfigurationList(in *AuthConfigurationList, out *componentconfig.AuthConfigurationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthConfigurationList_To_componentconfig_AuthConfigurationList(in, out, s)
}

func autoConvert_componentconfig_AuthConfigurationList_To_v1alpha1_AuthConfigurationList(in *componentconfig.AuthConfigurationList, out *AuthConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthConfiguration, len(*in))
		for i := range *in {
			if err := Convert_componentconfig_AuthConfiguration_To_v1alpha1_AuthConfiguration(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_componentconfig_AuthConfigurationList_To_v1alpha1_AuthConfigurationList is an autogenerated conversion function.
func Convert_componentconfig_AuthConfigurationList_To_v1alpha1_AuthConfigurationList(in *componentconfig.AuthConfigurationList, out *AuthConfigurationList, s conversion.Scope) error {
	return autoConvert_componentconfig_AuthConfigurationList_To_v1alpha1_AuthConfigurationList(in, out, s)
}

func autoConvert_v1alpha1_AuthProvider_To_componentconfig_AuthProvider(in *AuthProvider, out *componentconfig.AuthProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Description = in.Description
	if err := Convert_v1alpha1_OAuthConfig_To_componentconfig_OAuthConfig(&in.OAuthConfig, &out.OAuthConfig, s); err != nil {
		return err
	}
	out.PermitEmails = in.PermitEmails
	return nil
}

// Convert_v1alpha1_AuthProvider_To_componentconfig_AuthProvider is an autogenerated conversion function.
func Convert_v1alpha1_AuthProvider_To_componentconfig_AuthProvider(in *AuthProvider, out *componentconfig.AuthProvider, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthProvider_To_componentconfig_AuthProvider(in, out, s)
}

func autoConvert_componentconfig_AuthProvider_To_v1alpha1_AuthProvider(in *componentconfig.AuthProvider, out *AuthProvider, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Description = in.Description
	if err := Convert_componentconfig_OAuthConfig_To_v1alpha1_OAuthConfig(&in.OAuthConfig, &out.OAuthConfig, s); err != nil {
		return err
	}
	out.PermitEmails = in.PermitEmails
	return nil
}

// Convert_componentconfig_AuthProvider_To_v1alpha1_AuthProvider is an autogenerated conversion function.
func Convert_componentconfig_AuthProvider_To_v1alpha1_AuthProvider(in *componentconfig.AuthProvider, out *AuthProvider, s conversion.Scope) error {
	return autoConvert_componentconfig_AuthProvider_To_v1alpha1_AuthProvider(in, out, s)
}

func autoConvert_v1alpha1_AuthProviderList_To_componentconfig_AuthProviderList(in *AuthProviderList, out *componentconfig.AuthProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]componentconfig.AuthProvider, len(*in))
		for i := range *in {
			if err := Convert_v1alpha1_AuthProvider_To_componentconfig_AuthProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_v1alpha1_AuthProviderList_To_componentconfig_AuthProviderList is an autogenerated conversion function.
func Convert_v1alpha1_AuthProviderList_To_componentconfig_AuthProviderList(in *AuthProviderList, out *componentconfig.AuthProviderList, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthProviderList_To_componentconfig_AuthProviderList(in, out, s)
}

func autoConvert_componentconfig_AuthProviderList_To_v1alpha1_AuthProviderList(in *componentconfig.AuthProviderList, out *AuthProviderList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthProvider, len(*in))
		for i := range *in {
			if err := Convert_componentconfig_AuthProvider_To_v1alpha1_AuthProvider(&(*in)[i], &(*out)[i], s); err != nil {
				return err
			}
		}
	} else {
		out.Items = nil
	}
	return nil
}

// Convert_componentconfig_AuthProviderList_To_v1alpha1_AuthProviderList is an autogenerated conversion function.
func Convert_componentconfig_AuthProviderList_To_v1alpha1_AuthProviderList(in *componentconfig.AuthProviderList, out *AuthProviderList, s conversion.Scope) error {
	return autoConvert_componentconfig_AuthProviderList_To_v1alpha1_AuthProviderList(in, out, s)
}

func autoConvert_v1alpha1_GenerateKubeconfig_To_componentconfig_GenerateKubeconfig(in *GenerateKubeconfig, out *componentconfig.GenerateKubeconfig, s conversion.Scope) error {
	out.Server = in.Server
	out.Name = in.Name
	return nil
}

// Convert_v1alpha1_GenerateKubeconfig_To_componentconfig_GenerateKubeconfig is an autogenerated conversion function.
func Convert_v1alpha1_GenerateKubeconfig_To_componentconfig_GenerateKubeconfig(in *GenerateKubeconfig, out *componentconfig.GenerateKubeconfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_GenerateKubeconfig_To_componentconfig_GenerateKubeconfig(in, out, s)
}

func autoConvert_componentconfig_GenerateKubeconfig_To_v1alpha1_GenerateKubeconfig(in *componentconfig.GenerateKubeconfig, out *GenerateKubeconfig, s conversion.Scope) error {
	out.Server = in.Server
	out.Name = in.Name
	return nil
}

// Convert_componentconfig_GenerateKubeconfig_To_v1alpha1_GenerateKubeconfig is an autogenerated conversion function.
func Convert_componentconfig_GenerateKubeconfig_To_v1alpha1_GenerateKubeconfig(in *componentconfig.GenerateKubeconfig, out *GenerateKubeconfig, s conversion.Scope) error {
	return autoConvert_componentconfig_GenerateKubeconfig_To_v1alpha1_GenerateKubeconfig(in, out, s)
}

func autoConvert_v1alpha1_OAuthConfig_To_componentconfig_OAuthConfig(in *OAuthConfig, out *componentconfig.OAuthConfig, s conversion.Scope) error {
	out.ClientID = in.ClientID
	out.ClientSecret = in.ClientSecret
	return nil
}

// Convert_v1alpha1_OAuthConfig_To_componentconfig_OAuthConfig is an autogenerated conversion function.
func Convert_v1alpha1_OAuthConfig_To_componentconfig_OAuthConfig(in *OAuthConfig, out *componentconfig.OAuthConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OAuthConfig_To_componentconfig_OAuthConfig(in, out, s)
}

func autoConvert_componentconfig_OAuthConfig_To_v1alpha1_OAuthConfig(in *componentconfig.OAuthConfig, out *OAuthConfig, s conversion.Scope) error {
	out.ClientID = in.ClientID
	out.ClientSecret = in.ClientSecret
	return nil
}

// Convert_componentconfig_OAuthConfig_To_v1alpha1_OAuthConfig is an autogenerated conversion function.
func Convert_componentconfig_OAuthConfig_To_v1alpha1_OAuthConfig(in *componentconfig.OAuthConfig, out *OAuthConfig, s conversion.Scope) error {
	return autoConvert_componentconfig_OAuthConfig_To_v1alpha1_OAuthConfig(in, out, s)
}
