// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: pkg/keystore/pb/keystore.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyType int32

const (
	KeyType_KEYTYPE_UNKNOWN   KeyType = 0
	KeyType_KEYTYPE_SECRETBOX KeyType = 1
)

// Enum value maps for KeyType.
var (
	KeyType_name = map[int32]string{
		0: "KEYTYPE_UNKNOWN",
		1: "KEYTYPE_SECRETBOX",
	}
	KeyType_value = map[string]int32{
		"KEYTYPE_UNKNOWN":   0,
		"KEYTYPE_SECRETBOX": 1,
	}
)

func (x KeyType) Enum() *KeyType {
	p := new(KeyType)
	*p = x
	return p
}

func (x KeyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeyType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_keystore_pb_keystore_proto_enumTypes[0].Descriptor()
}

func (KeyType) Type() protoreflect.EnumType {
	return &file_pkg_keystore_pb_keystore_proto_enumTypes[0]
}

func (x KeyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeyType.Descriptor instead.
func (KeyType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_keystore_pb_keystore_proto_rawDescGZIP(), []int{0}
}

type EncryptionMethod int32

const (
	EncryptionMethod_ENCRYPTIONMETHOD_UNKNOWN   EncryptionMethod = 0
	EncryptionMethod_ENCRYPTIONMETHOD_SECRETBOX EncryptionMethod = 1
)

// Enum value maps for EncryptionMethod.
var (
	EncryptionMethod_name = map[int32]string{
		0: "ENCRYPTIONMETHOD_UNKNOWN",
		1: "ENCRYPTIONMETHOD_SECRETBOX",
	}
	EncryptionMethod_value = map[string]int32{
		"ENCRYPTIONMETHOD_UNKNOWN":   0,
		"ENCRYPTIONMETHOD_SECRETBOX": 1,
	}
)

func (x EncryptionMethod) Enum() *EncryptionMethod {
	p := new(EncryptionMethod)
	*p = x
	return p
}

func (x EncryptionMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptionMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_keystore_pb_keystore_proto_enumTypes[1].Descriptor()
}

func (EncryptionMethod) Type() protoreflect.EnumType {
	return &file_pkg_keystore_pb_keystore_proto_enumTypes[1]
}

func (x EncryptionMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptionMethod.Descriptor instead.
func (EncryptionMethod) EnumDescriptor() ([]byte, []int) {
	return file_pkg_keystore_pb_keystore_proto_rawDescGZIP(), []int{1}
}

type KeySetData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys     []*KeyData `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	ActiveId int32      `protobuf:"varint,2,opt,name=active_id,json=activeId,proto3" json:"active_id,omitempty"`
	KeyType  KeyType    `protobuf:"varint,3,opt,name=key_type,json=keyType,proto3,enum=pb.KeyType" json:"key_type,omitempty"`
}

func (x *KeySetData) Reset() {
	*x = KeySetData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_keystore_pb_keystore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeySetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySetData) ProtoMessage() {}

func (x *KeySetData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_keystore_pb_keystore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySetData.ProtoReflect.Descriptor instead.
func (*KeySetData) Descriptor() ([]byte, []int) {
	return file_pkg_keystore_pb_keystore_proto_rawDescGZIP(), []int{0}
}

func (x *KeySetData) GetKeys() []*KeyData {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *KeySetData) GetActiveId() int32 {
	if x != nil {
		return x.ActiveId
	}
	return 0
}

func (x *KeySetData) GetKeyType() KeyType {
	if x != nil {
		return x.KeyType
	}
	return KeyType_KEYTYPE_UNKNOWN
}

type KeyData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Secret  []byte `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Created int64  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *KeyData) Reset() {
	*x = KeyData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_keystore_pb_keystore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeyData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyData) ProtoMessage() {}

func (x *KeyData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_keystore_pb_keystore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyData.ProtoReflect.Descriptor instead.
func (*KeyData) Descriptor() ([]byte, []int) {
	return file_pkg_keystore_pb_keystore_proto_rawDescGZIP(), []int{1}
}

func (x *KeyData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *KeyData) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

func (x *KeyData) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

type EncryptedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptionMethod EncryptionMethod `protobuf:"varint,1,opt,name=encryption_method,json=encryptionMethod,proto3,enum=pb.EncryptionMethod" json:"encryption_method,omitempty"`
	KeyId            int32            `protobuf:"varint,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Nonce            []byte           `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext       []byte           `protobuf:"bytes,4,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
}

func (x *EncryptedData) Reset() {
	*x = EncryptedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_keystore_pb_keystore_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedData) ProtoMessage() {}

func (x *EncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_keystore_pb_keystore_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedData.ProtoReflect.Descriptor instead.
func (*EncryptedData) Descriptor() ([]byte, []int) {
	return file_pkg_keystore_pb_keystore_proto_rawDescGZIP(), []int{2}
}

func (x *EncryptedData) GetEncryptionMethod() EncryptionMethod {
	if x != nil {
		return x.EncryptionMethod
	}
	return EncryptionMethod_ENCRYPTIONMETHOD_UNKNOWN
}

func (x *EncryptedData) GetKeyId() int32 {
	if x != nil {
		return x.KeyId
	}
	return 0
}

func (x *EncryptedData) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptedData) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

var File_pkg_keystore_pb_keystore_proto protoreflect.FileDescriptor

var file_pkg_keystore_pb_keystore_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70,
	0x62, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x72, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x53, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1f, 0x0a, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x49, 0x64,
	0x12, 0x26, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x4b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x07, 0x6b, 0x65, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4b, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x9f, 0x01, 0x0a, 0x0d, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x11, 0x65, 0x6e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x10, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6b, 0x65,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6b, 0x65, 0x79, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x69, 0x70, 0x68, 0x65,
	0x72, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x63, 0x69, 0x70,
	0x68, 0x65, 0x72, 0x74, 0x65, 0x78, 0x74, 0x2a, 0x35, 0x0a, 0x07, 0x4b, 0x65, 0x79, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x4b, 0x45, 0x59, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4b, 0x45, 0x59, 0x54, 0x59,
	0x50, 0x45, 0x5f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x42, 0x4f, 0x58, 0x10, 0x01, 0x2a, 0x50,
	0x0a, 0x10, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x1c, 0x0a, 0x18, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x49, 0x4f, 0x4e,
	0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x4e, 0x43, 0x52, 0x59, 0x50, 0x54, 0x49, 0x4f, 0x4e, 0x4d, 0x45,
	0x54, 0x48, 0x4f, 0x44, 0x5f, 0x53, 0x45, 0x43, 0x52, 0x45, 0x54, 0x42, 0x4f, 0x58, 0x10, 0x01,
	0x42, 0x1e, 0x5a, 0x1c, 0x6b, 0x6f, 0x70, 0x65, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6b, 0x65, 0x79, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_keystore_pb_keystore_proto_rawDescOnce sync.Once
	file_pkg_keystore_pb_keystore_proto_rawDescData = file_pkg_keystore_pb_keystore_proto_rawDesc
)

func file_pkg_keystore_pb_keystore_proto_rawDescGZIP() []byte {
	file_pkg_keystore_pb_keystore_proto_rawDescOnce.Do(func() {
		file_pkg_keystore_pb_keystore_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_keystore_pb_keystore_proto_rawDescData)
	})
	return file_pkg_keystore_pb_keystore_proto_rawDescData
}

var file_pkg_keystore_pb_keystore_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_keystore_pb_keystore_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_keystore_pb_keystore_proto_goTypes = []interface{}{
	(KeyType)(0),          // 0: pb.KeyType
	(EncryptionMethod)(0), // 1: pb.EncryptionMethod
	(*KeySetData)(nil),    // 2: pb.KeySetData
	(*KeyData)(nil),       // 3: pb.KeyData
	(*EncryptedData)(nil), // 4: pb.EncryptedData
}
var file_pkg_keystore_pb_keystore_proto_depIdxs = []int32{
	3, // 0: pb.KeySetData.keys:type_name -> pb.KeyData
	0, // 1: pb.KeySetData.key_type:type_name -> pb.KeyType
	1, // 2: pb.EncryptedData.encryption_method:type_name -> pb.EncryptionMethod
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_keystore_pb_keystore_proto_init() }
func file_pkg_keystore_pb_keystore_proto_init() {
	if File_pkg_keystore_pb_keystore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_keystore_pb_keystore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeySetData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_keystore_pb_keystore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeyData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_keystore_pb_keystore_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_keystore_pb_keystore_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_keystore_pb_keystore_proto_goTypes,
		DependencyIndexes: file_pkg_keystore_pb_keystore_proto_depIdxs,
		EnumInfos:         file_pkg_keystore_pb_keystore_proto_enumTypes,
		MessageInfos:      file_pkg_keystore_pb_keystore_proto_msgTypes,
	}.Build()
	File_pkg_keystore_pb_keystore_proto = out.File
	file_pkg_keystore_pb_keystore_proto_rawDesc = nil
	file_pkg_keystore_pb_keystore_proto_goTypes = nil
	file_pkg_keystore_pb_keystore_proto_depIdxs = nil
}
